### ISSUE TITLE
Opening on New Tab deactivate a addon

### ISSUE THREAD

**Issue by Aspet2** [Taknok/youtube-auto-like#12]
## Expected Behavior
Addon should press "like" button every time. Doesn't matter how you open video.

## Actual Behavior
If you open Youtube video in new window ( pressing mouse scroll ) addon don't press "like" button. It do it when you refresh page, or just simple open in  that same window.

## Steps to Reproduce the Problem

  1. Go to Youtube and play movie by open it in new tab ( PPM > Open in new tab, or press scroll down )
  2. Addon don't work, "like" button its not pressed
  3. Refresh page using f5 or reload button, and addon will work. But its not normal behavior.

## Specifications

  - Version: 2.2.1
  - Platform: Windows 10 pro x64
  - Subsystem: Firefox 63

**Comment by Taknok** [comment]
Hi,
This issue is really strange to me, because I mainly use "open in a new tab" to keep my youtube feed on the 1st tab and I don't have your issue. You can see in the video linked.
Could you send the screen shot of the console in dev mode (`ctrl + shift + I`) (This feature is also shown in the video) ?
Finally, what are your settings in the plugin ?
Video : https://youtu.be/WX41hkL4lqc
