### ISSUE TITLE
ReferenceError: browser is not defined

### ISSUE THREAD

**Issue by leodoi3** [Taknok/youtube-auto-like#53]
I'm trying to fork your repo to have it also work for Chrome so it can be sideloaded.  When i load it from developer menu this is what errors I get:
![image](https://user-images.githubusercontent.com/46114199/135022734-e3405593-0988-4590-b553-b277fdad6ab4.png)

I have little to no experience with extensions so I dont know what to do.

**Comment by Taknok** [comment]
My repo is forked from the [Chrome extension](https://github.com/austencm/youtube-auto-like) ^^ and this extension was banned from the chrome store during the [last youtube ban](https://github.com/austencm/youtube-auto-like/issues/61) of discord bot and others programs.

This being said, you can found a guide to port an extension from chrome to firefox [here](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Build_a_cross_browser_extension). In your screenshot the issue is that `browser` is the object for Firefox browser, the Chrome browser is manipulated with `chrome`, but all of this is explained in the documentation linked.

Another problem you may encounter and will not be mentioned in the documentation linked, is that youtube change according to the browser you are using. Meaning some HTML elements exists on Chrome while not on Firefox or Safari and the reverse is also true. I would suggest you to run a Firefox with the addon and a Chrome with your porting to see the differences.
