### ISSUE TITLE
Autolike pages on Facebook too

### ISSUE THREAD

**Issue by budders84** [Taknok/youtube-auto-like#58]
**Expected Behavior**
LIKE ONLY YOUTUBE VIDEOS 
**Actual Behavior**
IT LIKES ALL FACEBOOK PAGES, AND PAGES THAT ARE RECCOMENDED BELOW THAT ON FACEBOOK. SO IF YOU VISIT ONE HOT GIRL PAGE ON FB IT LIKES ALL ASSOCIATED HOT GIRLS IN RECCOMENDED.

**Specification**
W10, FIREFOX

**Comment by Taknok** [comment]
This is really strange, because this line prevent script from execution in any other pages than youtube.com
https://github.com/Taknok/youtube-auto-like/blob/6c2579b58202cf120c5deb1ac27c0ed8b3a7f374/app/manifest.json#L27
 This isolation is performed by Firefox, so if you have this kind of weird behavior, or you have another malicious addon or something is broken at Firefox level and I cannot do anything :/

A video of the behavior could help to investigate this issue.

**Comment by budders84** [comment]
SORRY HIGH AF, YOU ARE CORRECT.
BUT I STILL GET WIERD GLITCHES, I ADD CREATORS, IT DOESNT LIKE THEM. MY CREATOR LIST HAS DISAPEARED. SOMETIMES IT DOESNT LIKE THE VID, OTHER TIMES IT LIKES ALL VIDS. NOT SURE WHAT IM DOING WRONG, MAYBE TOO MUCH CRACK
   On Wednesday, March 9, 2022, 02:59:58 AM EST, Pg ***@***.***> wrote:  
 
 


This is really strange, because this line prevent script from execution in any other pages than youtube.com
https://github.com/Taknok/youtube-auto-like/blob/6c2579b58202cf120c5deb1ac27c0ed8b3a7f374/app/manifest.json#L27
This isolation is performed by Firefox, so if you have this kind of weird behavior, or you have another malicious addon or something is broken at Firefox level and I cannot do anything :/

A video of the behavior could help to investigate this issue.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
