### ISSUE TITLE
i cant put anyone in a list

### ISSUE THREAD

**Issue by Githuber56** [Taknok/youtube-auto-like#67]
when i try to put anyone in a list it does not work. This is also the case for "Youtube Auto Dislike"

**Comment by Taknok** [comment]
Even if "YouTube auto dislike" is based on my plugin, I'm not the maintainer of "YouTube auto Dislike" and I do not agree with the philosophy behind it.

Regards the issue here, could you provide mode details ? As where you goes, where you click ?

The current normal process is:
1. to go to a youtube video or youtube channel
2. Click youtube auto like icon
3. Click add creator button

The add creator is only visible on a youtube video ou youtube channel page.

**Comment by Taknok** [comment]
Hi, 
Any update on this ?

**Comment by Githuber56** [comment]
thanks for helping me man , have a great day

**Comment by Taknok** [comment]
Ok, glad to help !
